version: '3.1'
services: 
  pgsql:
    container_name: pino_pg_db
    image: postgres:14.1-alpine
    ports: 
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}