on:
  push:
    branches:
      - master
name: release
  jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: GoogleCloudPlatform/release-please-action@v1.3.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: node
            package-name: pino-pg
        - uses: actions/checkout@v2
          with:
            node-version: 12
            registry-url: 'https://registry.npmjs.org'
          if: ${{ steps.release.outputs.release_created }}
        - run: npm ci
          if: ${{ steps.release.outputs.release_created }}
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          if: ${{ steps.release.outputs.release_created }}
