name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - uses: m4nu56/postgresql-action@v1
      with:
        postgresql db: test-database
        postgresql user: postgres
        postgresql password: root
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
      env:
        CI: true